--: Improved installation process.
Now it's smarter!

diff --git a/install b/install
--- a/install
+++ b/install
@@ -31,29 +31,78 @@ INSTALL_FILE="$INSTALL/ls-git"
 # ----------------------------------------------------------------------------------------------------------------------
 # Dependency check:
 
-depcheck() {
-	printf "Checking for dependency %-15s " "'$1'..."
-	if ! command -v "$1" &>/dev/null; then
-		echo "Missing"
-		exit 1
+depcheck_perl() {
+	printf "Checking for module %-30s " "'$1'..."
+	if echo "use $1;" | perl &>/dev/null; then
+		echo "OK"
+		return 0
 	fi
 
-	echo "OK"
+	echo "Missing"
+	echo "Installing..."
+	cpan install "$1" && return 0;
+
+	echo "------"
+	echo "FATAL: Failed to install module: $1";
+	exit 1
 }
 
+depcheck() {
+	printf "Checking for dependency %-26s " "'$1'..."
+	if command -v "$1" &>/dev/null; then
+		echo "OK"
+		return 0
+	fi
+
+	echo "Missing"
+	exit 1
+}
+
+# Command dependencies.
+depcheck 'cpan'
 depcheck 'perl'
 depcheck 'git'
 depcheck 'tput'
 
+# Module dependencies.
+while read -r module; do
+	depcheck_perl "$module"
+done < <(grep "^use [A-Z][A-Za-z\:]\{1,\}" "$HERE/ls-git.pl" | sed 's/use \([A-Za-z\:]\{1,\}\).*/\1/' | sort -r )
+
+# ----------------------------------------------------------------------------------------------------------------------
+# Preproccess:
+
+echo "Preprocessing..."
+tempfile="$(mktemp "$(mktemp -d)"/'ls-git.pl')"
+
+while IFS='' read -r line; do
+	if [ "${line:0:7}" = "require" ]; then
+		file="$(sed "s/^require *(\{0,1\}['\"]\([A-Za-z0-9\/\.\-\]\{1,\}\).*\$/\1/" <<< "$line")"
+		if [ -f "$file" ]; then
+			echo "Embedding: $file"
+
+			echo "# <PREPROCESSOR> INCLUDE: $file" >> "$tempfile"
+			cat "$file" >> "$tempfile"
+			echo "# <PREPROCESSOR> END:     $file" >> "$tempfile"
+		else
+			echo "------"
+			echo "FATAL: Failed to embed file: $file";
+			exit 1
+		fi
+	fi
+	echo "$line" >> "$tempfile"
+done < "$HERE/ls-git.pl"
+
 # ----------------------------------------------------------------------------------------------------------------------
 # Install:
+
 echo "Installing to: $INSTALL"
 if [ -n "$MINIFY" ] && command -v perltidy &>/dev/null; then
 	# Install minified.
-	perltidy --mangle --delete-all-comments "$HERE/ls-git.pl" -o "$INSTALL_FILE"
+	perltidy --mangle --delete-all-comments "$tempfile" -o "$INSTALL_FILE"
 else
 	# Install original.
-	cp "$HERE/ls-git.pl" "$INSTALL_FILE"
+	cp "$tempfile" "$INSTALL_FILE"
 fi
 
 chmod 755 "$INSTALL_FILE"
